version: '3.7'
services:
  test-app:
    build: .
    container_name: test-app
    ports:
      - "80:8080"
    volumes:
      - ./api:/var/www/html
      - ./conf/php.conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  database:
    container_name: test-db
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - tes_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database

volumes:
  tes_mysql_data: {}