version: '3.7'
services:
  php:
    container_name: test-app
    build: ./docker-resources/php-fpm
    volumes:
      - ./api/:/var/www/html:cached
      - ./api/var/logs/project:/var/www/html/var/log:cached
    environment:
      PHP_IDE_CONFIG: "serverName=test-app"
      XDEBUG_CONFIG: "start_with_request=yes client_host=host.docker.internal"
  nginx:
    build: ./docker-resources/nginx
    ports:
      - "80:80"
    volumes:
      - ./api/var/logs/nginx:/var/log/nginx:cached
      - ./api/:/var/www/html:cached

  database:
    container_name: test-db
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - tes_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database

volumes:
  tes_mysql_data: {}